cache: bundler
language: ruby
sudo: false

addons:
    apt:
        packages:
            - aspell
            - aspell-en
            - aspell-fr
            - jq

install:
    - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script:
    - bundle exec rake lint
    - bundle exec rake test

after_success:
    - ./bin/deploy-pr.sh

before_deploy:
    - pip install --user awscli

deploy:
    provider: script
    skip_cleanup: true
    script: aws s3 sync _site/ s3://blog.eleven-labs.com/ --delete
    on:
        branch: master

after_deploy:
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"
    - ./bin/notify-slack.sh
    - bundle exec rake deploy
