# SITE CONFIGURATION
title: Blog Eleven Labs
description: Blog Eleven Labs
url: https://blog.eleven-labs.com
twitter:
    username: Eleven_Labs
logo: /img/avatar.png
social:
    name: Eleven Labs
    links:
        - https://twitter.com/Eleven_Labs
        - https://www.facebook.com/11Labs
        - https://www.linkedin.com/company/eleven-labs
        - https://www.youtube.com/channel/UCt_NukjmUm4whjmbMuZ0MMw
        - https://github.com/eleven-labs
        - https://stackoverflow.com/jobs/companies/eleven-labs

baseurl: ""

# LANGUAGE-SPECIFIC CONFIGURATION
default_lang: fr
languages: ["fr", "en"]
exclude_from_localizations: ["authors", "css", "fonts", "img", "js"]
localized_posts_dir: _posts

# THEME-SPECIFIC CONFIGURATION
theme_settings:
    # Meta
    site_web_eleven: https://eleven-labs.com/
    site_web_eleven_rencontres: https://eleven-labs.com/rencontres
    # title: Eleven Labs - Le Blog
    brand : Eleven Labs
    le_blog : LE BLOG
    le_site : LE SITE
    gravatar:
    description: A website with blog posts and pages

    # Header and footer
    copyright: ElevenLabs © 2019
    phone_number: +33 1 82 83 11 75
    adress: 15, avenue de la Grande Armée
    post_code: 75016 PARIS

    # Icons
    rss: /feed.xml
    email_address:
    behance:
    bitbucket:
    dribbble:
    facebook: 11Labs
    flickr:
    github: eleven-labs
    google_plus:
    instagram:
    linkedin: https://fr.linkedin.com/company/eleven-labs
    pinterest:
    reddit:
    soundcloud:
    stack_exchange:
    steam:
    tumblr:
    twitter: eleven_labs
    wordpress:
    youtube:
    corporate:
    corporate_logo: /img/follow/eleven.svg
    welcome_to_the_jungle: https://www.welcometothejungle.co/fr/companies/eleven-labs
    welcome_to_the_jungle_logo: /img/follow/welcome_to_the_jungle.svg

    # Scripts
    google_analytics: UA-99013054-1
    disqus_shortname: blog-eleven-labs

    # Post navigation
    post_navigation: false

    # Share button
    share_button: true

# PAGINATION
paginate: 10
paginate_path: "/page/:num/"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
    style: :compressed
plugins:
    - jekyll-paginate
    - jekyll-multiple-languages-plugin
    - jekyll-seo-tag
    - jekyll-feed
    - amp-jekyll
    - uglifier
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - CNAME
    - CODE_OF_CONDUCT.md
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile
    - _authors/TEMPLATE-AUTOR
    - bin
    - vendor
    - docker-compose.yml

collections:
  authors:
    output: true
