# SITE CONFIGURATION
title: Blog Eleven Labs
description: Blog Eleven Labs
url: https://eleven-labs.github.io
twitter:
    username: eleven-labs
logo: /img/avatar.png
social:
    name: Eleven Labs
    links:
        - https://twitter.com/eleven-labs
        - https://www.facebook.com/11Labs
        - https://www.linkedin.com/company/eleven-labs
        - https://www.youtube.com/channel/UCt_NukjmUm4whjmbMuZ0MMw
        - https://github.com/eleven-labs
        - https://stackoverflow.com/jobs/companies/eleven-labs
baseurl:

# THEME-SPECIFIC CONFIGURATION
theme_settings:
    # Meta
    title: Eleven Labs
    avatar: avatar.png
    gravatar:
    description: A website with blog posts and pages

    # Header and footer text
    header_text: <img src="/img/fg-header.png" />
    header_text_feature_image: img/bg-header.png
    footer_text: >
        Powered by
        <a href="http://jekyllrb.com">Jekyll</a>
        with
        <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

    # Icons
    rss: false
    email_address: wilson@eleven-labs.com
    behance:
    bitbucket:
    dribbble:
    facebook: 11Labs
    flickr:
    github: eleven-labs
    google_plus:
    instagram:
    linkedin: https://fr.linkedin.com/company/eleven-labs
    pinterest:
    reddit:
    soundcloud:
    stack_exchange: http://stackoverflow.com/jobs/companies/eleven-labs
    steam:
    tumblr:
    twitter: eleven_labs
    wordpress:
    youtube: UCt_NukjmUm4whjmbMuZ0MMw

    # Scripts
    google_analytics: UA-99013054-1
    disqus_shortname: eleven-labs-github-io
    muut_community_name:

    # Localization strings
    str_follow_on: Suivez nous sur
    str_rss_follow:
    str_email: Email
    str_next: Suivant
    str_prev: Précédent
    str_continue_reading: Lire l'article

    # Colours, typography and padding
    google_fonts: Cabin

    # Post navigation
    post_navigation: false

# PAGINATION
paginate: 5
paginate_path: blog/page:num

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
    style: :compressed
gems:
    - jekyll-paginate
    - jekyll-seo-tag
