# SITE CONFIGURATION
title: Blog Eleven Labs
description: Blog Eleven Labs
url: http://blog.eleven-labs.com
twitter:
    username: Eleven_Labs
logo: /img/avatar.png
social:
    name: Eleven Labs
    links:
        - https://twitter.com/Eleven_Labs
        - https://www.facebook.com/11Labs
        - https://www.linkedin.com/company/eleven-labs
        - https://www.youtube.com/channel/UCt_NukjmUm4whjmbMuZ0MMw
        - https://github.com/eleven-labs
        - https://stackoverflow.com/jobs/companies/eleven-labs
baseurl:

# THEME-SPECIFIC CONFIGURATION
theme_settings:
    # Meta
    title: Eleven Labs
    gravatar:
    description: A website with blog posts and pages

    # Header and footer text
    header_text_fg_image: img/fg-header.png
    header_text_bg_image: img/bg-header.png
    footer_text: To infinity and beyond !

    # Icons
    rss: /feed.xml
    email_address:
    behance:
    bitbucket:
    dribbble:
    facebook: 11Labs
    flickr:
    github: eleven-labs
    google_plus:
    instagram:
    linkedin: https://fr.linkedin.com/company/eleven-labs
    pinterest:
    reddit:
    soundcloud:
    stack_exchange:
    steam:
    tumblr:
    twitter: eleven_labs
    wordpress:
    youtube:

    # Scripts
    google_analytics: UA-99013054-1
    disqus_shortname: blog-eleven-labs
    muut_community_name:

    # Localization strings
    str_follow_on: Suivez-nous sur
    str_rss_follow: Ajoutez-nous à votre veille
    str_email: Email
    str_next: Suivant
    str_prev: Précédent
    str_continue_reading: Lire l'article

    # Post navigation
    post_navigation: false

    # Share button
    share_button: true

# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"

# ALGOLIA
algolia:
    application_id: '5IGTHBX5JS'
    index_name:     'blog_eleven'

exclude: [vendor, _authors/TEMPLATE-AUTOR]

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
    style: :compressed
gems:
    - jekyll-paginate
    - jekyll-seo-tag
    - algoliasearch-jekyll
    - jekyll-feed
    - amp-jekyll

collections:
  authors:
    output: true
